### ISSUE TITLE
Randomly fprintd service stops

### ISSUE THREAD

**Issue by rodude123** [Popax21/synaTudor#10]
Randomly the `fprintd` service stops and says `tudor failed` and then won't work again until I manually say start the `fprintd` service

**Comment by Popax21** [comment]
Can you attach the output of both `sudo journalctl -b -u fprintd.service` and `sudo journalctl -b -u tudor-host-launcher.service`? Note that it's normal for fprintd to shut itself after some time when not used - it should automatically start again when needed.

**Comment by rodude123** [comment]
It got fixed by doing a hard reboot
