### ISSUE TITLE
Whenever fprintd launches, tudor-host-launcher.service loses DBus name

### ISSUE THREAD

**Issue by berkentekin** [Popax21/synaTudor#26]
I'm on Fedora 40, GNOME 46
tudor-host-launcher.service runs fine when I start it, but as soon as I attempt to start fprintd, or go to Settings->System->Users, tudor-host-launcher immediately gets deactivated.

I've compiled fprintd, libfprint-tod myself.

Is there a way to solve this issue?

```
○ tudor-host-launcher.service - Tudor host launcher DBus service
     Loaded: loaded (/usr/lib/systemd/system/tudor-host-launcher.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
             /etc/systemd/system/tudor-host-launcher.service.d
             └─override.conf
     Active: inactive (dead) since Fri 2024-05-17 22:12:59 CEST; 1s ago
   Duration: 26.883s
    Process: 15354 ExecStart=/usr/sbin/tudor/tudor_host_launcher (code=killed, signal=TERM)
   Main PID: 15354 (code=killed, signal=TERM)
        CPU: 48ms

May 17 22:12:32 dunkelheit systemd[1]: Starting tudor-host-launcher.service - Tudor host launcher DBus service...
May 17 22:12:32 dunkelheit tudor_host_laun[15354]: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
May 17 22:12:32 dunkelheit systemd[1]: Started tudor-host-launcher.service - Tudor host launcher DBus service.
May 17 22:12:32 dunkelheit tudor_host_laun[15354]: Acquired DBus name 'net.reactivated.TudorHostLauncher'
May 17 22:12:59 dunkelheit tudor_host_laun[15354]: Launched Tudor host process ID 1 PID 15508 for USB bus 0x0001 addr 0x0005
May 17 22:12:59 dunkelheit tudor_host_laun[15354]: Lost DBus name 'net.reactivated.TudorHostLauncher'!
May 17 22:12:59 dunkelheit systemd[1]: tudor-host-launcher.service: Deactivated successfully.

```

**Comment by Popax21** [comment]
> I'm on Fedora 40, GNOME 46 tudor-host-launcher.service runs fine when I start it, but as soon as I attempt to start fprintd, or go to Settings->System->Users, tudor-host-launcher immediately gets deactivated.
> 
> I've compiled fprintd, libfprint-tod myself.
> 
> Is there a way to solve this issue?
> 
> ```
> ○ tudor-host-launcher.service - Tudor host launcher DBus service
>      Loaded: loaded (/usr/lib/systemd/system/tudor-host-launcher.service; enabled; preset: disabled)
>     Drop-In: /usr/lib/systemd/system/service.d
>              └─10-timeout-abort.conf
>              /etc/systemd/system/tudor-host-launcher.service.d
>              └─override.conf
>      Active: inactive (dead) since Fri 2024-05-17 22:12:59 CEST; 1s ago
>    Duration: 26.883s
>     Process: 15354 ExecStart=/usr/sbin/tudor/tudor_host_launcher (code=killed, signal=TERM)
>    Main PID: 15354 (code=killed, signal=TERM)
>         CPU: 48ms
> 
> May 17 22:12:32 dunkelheit systemd[1]: Starting tudor-host-launcher.service - Tudor host launcher DBus service...
> May 17 22:12:32 dunkelheit tudor_host_laun[15354]: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
> May 17 22:12:32 dunkelheit systemd[1]: Started tudor-host-launcher.service - Tudor host launcher DBus service.
> May 17 22:12:32 dunkelheit tudor_host_laun[15354]: Acquired DBus name 'net.reactivated.TudorHostLauncher'
> May 17 22:12:59 dunkelheit tudor_host_laun[15354]: Launched Tudor host process ID 1 PID 15508 for USB bus 0x0001 addr 0x0005
> May 17 22:12:59 dunkelheit tudor_host_laun[15354]: Lost DBus name 'net.reactivated.TudorHostLauncher'!
> May 17 22:12:59 dunkelheit systemd[1]: tudor-host-launcher.service: Deactivated successfully.
> ```

`tudor-host-launcher` should automatically activate when needed, so you don't need to start it manually.

**Comment by berkentekin** [comment]
I see, thank you. I suppose my fingerprint reader (06cb:00be) just isn't supported then
